[build]
  publish        = "public"
  functions      = "netlify/functions"
  edge_functions = "netlify/edge-functions"

[[edge_functions]]
  function = "rate-limit"
  path     = "/api/*"

[[edge_functions]]
  function = "kill-switch"
  path     = "/*"

[[edge_functions]]
  function = "protect-trial"
  path     = "/trial/*"
# --- security headers ---
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; base-uri 'none'; object-src 'none'; frame-ancestors 'none'; img-src 'self' https: data:; font-src 'self' data:; style-src 'self' 'unsafe-inline' https://unpkg.com; script-src 'self' https://unpkg.com; connect-src 'self'; upgrade-insecure-requests;"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=()"
# --- end security headers ---
[[redirects]]
  from = "/security.txt"
  to   = "/.well-known/security.txt"
  status = 200
