name: Build & Deploy Feeds

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Netlify CLI
        run: npm i -g netlify-cli

      - name: Build feed snapshots
        run: node scripts/build-feeds.mjs

      - name: Deploy to Netlify (prod)
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: netlify deploy --prod --dir=public
